# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/


# Appearance
appearance:
  mode: light
  color: blue
  favicon: "media/icon_hu4166356570829923896.png"



# Site header
header:
  navbar:
    enable: true
    blox: floating-theme-toggler

# Site footer
footer:
  copyright:
    notice: '© {year} Me'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
